### ISSUE TITLE
TemplateURL must reference a valid S3 object to which you have access

### ISSUE THREAD

**Issue by xied75** [coreos/coreos-kubernetes#175] opened 2015-12-01 15:48 UTC
Dear all,

Just tried a build on the head "commit 54ee4b0d3a00dbc3b1f67813c05420ef4dc24ad1" to try if I can modify instance size now.

It gives me this error:
```
Initialized TLS infrastructure
Wrote kubeconfig to /home/dong/aws/kube-aws/clusters/kube1/kubeconfig
Waiting for cluster creation...
Failed creating cluster: ValidationError: TemplateURL must reference a valid S3 object to which you have access.
	status code: 400, request id: dcea7543-9840-11e5-9d2a-85c10bacc209
```

I suppose it was trying to access a s3 with the commit hash other than a valid version number?

**Comment by aaronlevy** [comment] 2015-12-02 03:35
Hi @xied75,

Yes, the kube-aws tool will default to using the release version (if tagged) or commit (if untagged) when attempting to download the cluster assets. In this case because it was built off head, it seems the "version" it expects does not exist in the S3 bucket you are accessing.

However, you can also specify a custom location in the cluster.yaml file (first copy cluster.yaml.example to cluster.yaml) then specify a custom location/version: https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/aws/cluster.yaml.example#L41

**Comment by xied75** [comment] 2015-12-02 08:45
@aaronlevy Thanks for explaining. What I did then is uncomment this line and give it the last version number I know works:

```
artifactURL: https://coreos-kubernetes.s3.amazonaws.com/v0.2.0
```
Then it gives me this:

```
Initialized TLS infrastructure
Wrote kubeconfig to /home/dong/aws/kube-aws/clusters/kube1/kubeconfig
Waiting for cluster creation...
Failed creating cluster: ValidationError: Parameters: [WorkerRootVolumeSize, ControllerRootVolumeSize] do not exist in the template
	status code: 400, request id: cdfe42ed-98d0-11e5-b7be-a7c0634d38c1
```

Which is the same as

**Comment by aaronlevy** [comment] 2015-12-04 20:19
I am going to close this as a duplicate of https://github.com/coreos/coreos-kubernetes/issues/172 -- but please re-open if that is not the case.

Per that issue this should be resolved in a new release that I should have done later today.

**Closed by aaronlevy** 2015-12-04 20:19 UTC
Labels: kind/question, platform/AWS
