### ISSUE TITLE
Add kube-ui into Multi-node AWS

### ISSUE THREAD

**Issue by dhoeric** [coreos/coreos-kubernetes#156] opened 2015-11-19 08:55 UTC
Hi, I want to add the kube-ui into cluster.
I tried to add `kube-ui-rc.yaml` & `kube-ui-svc.yml` into cluster by `kubectl ... create -f kube-ui-rc.yaml`.
But it only shows "Unauthorized" on the browser.

From: https://github.com/kubernetes/kubernetes/blob/7c660bc240223654403e11d299c84e53155af0f2/cluster/addons/kube-ui/kube-ui-rc.yaml

Is there any folks tried to add the kube-ui into aws kubernetes cluster?

**Comment by ankitforcode** [comment] 2015-11-20 06:38
@dhoeric There is already a PR for the same.

https://github.com/coreos/coreos-kubernetes/pull/145

**Comment by aaronlevy** [comment] 2015-11-24 01:51
Hi @dhoeric 

The easiest way to authenticate against the API and use the UI addon is to use `kubectl proxy` to authenticate using your kubeconfig:

```
> kubectl proxy
Starting to serve on 127.0.0.1:8001
```

Then you should be able to access the UI via your browser at: http://127.0.0.1:8001/ui

There is also an issue open to better document these steps: https://github.com/coreos/coreos-kubernetes/issues/163

**Comment by aaronlevy** [comment] 2015-12-04 19:51
Closing as duplicate of https://github.com/coreos/coreos-kubernetes/issues/163

**Closed by aaronlevy** 2015-12-04 19:51 UTC
Labels: reviewed/duplicate
