### ISSUE TITLE
e2e flakes in v1.2.2 release

### ISSUE THREAD

**Issue by pbx0** [coreos/coreos-kubernetes#409] opened 2016-04-14 00:19 UTC
Documenting e2e flakes for the v1.2.2 release of github.com/coreos/kubernetes. 

Failures:
```
[91m[1m[Fail] [0m[90mKubectl client [0m[0mSimple pod [0m[91m[1m[It] should support exec through an HTTP proxy [0m
[37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:256[0m

[91m[1m[Fail] [0m[90mServices [0m[91m[1m[It] should be able to change the type and ports of a service [0m
[37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1635[0m
```

The first failure seems to indicate a defect in the Jenkins host we are running and building the e2e test from. See: https://github.com/kubernetes/kubernetes/issues/15713

The second failure seems to be a more recently fixed flake: https://github.com/kubernetes/kubernetes/issues/22925

**Comment by aaronlevy** [comment] 2016-05-11 02:01
I'm going to close this as duplicate of: https://github.com/coreos/coreos-kubernetes/issues/380

We can track release-1.2 flakes there.

**Closed by aaronlevy** 2016-05-11 02:01 UTC
Labels: dependency/kubernetes, kind/bug, platform/AWS, priority/P1
