### ISSUE TITLE
AWS: nodes never register

### ISSUE THREAD

**Issue by bkeroackdsc** [coreos/coreos-kubernetes#370] opened 2016-03-30 22:46 UTC
After running ``kube-aws up``, the worker nodes never register with the controller (I've waited as long as 12 hours). I've verified that network communication works controller <--> worker, and controller IP is correct on the workers. I see no relevant errors in kube-proxy other than iptables errors (which apparently are benign?).

``cluster.yaml``:

```yaml
clusterName: test-kubernetes-1
externalDNSName: test-k8s-controller.foo.com
keyName: test-k8s
region: us-west-2
availabilityZone: us-west-2a
kmsKeyArn: "arn:aws:kms:us-west-2:xxxxxxxx:key/xxxxxxx"
controllerInstanceType: c4.large
controllerRootVolumeSize: 60
workerCount: 3
workerInstanceType: r3.large
workerRootVolumeSize: 60
vpcCIDR: "10.21.0.0/16"
instanceCIDR: "10.21.1.0/24"
controllerIP: "10.21.1.10"
serviceCIDR: "10.23.0.0/16"
podCIDR: "10.22.0.0/16"
dnsServiceIP: "10.23.1.10"
kubernetesVersion: v1.1.7_coreos.2
hyperkubeImageRepo: quay.io/coreos/hyperkube
```

On a worker:
```bash
core@ip-10-21-1-225 ~ $ docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
6cf808707d63        quay.io/coreos/hyperkube:v1.1.7_coreos.2   "/hyperkube proxy --m"   14 minutes ago      Up 14 minutes                           k8s_kube-proxy.3d3fad81_kube-proxy-ip-10-21-1-225_kube-system_849e5a7e323d985b742295309c5f414e_539b3142
c9c9c81fbd81        gcr.io/google_containers/pause:0.8.0       "/pause"                 14 minutes ago      Up 14 minutes                           k8s_POD.6d00e006_kube-proxy-ip-10-21-1-225_kube-system_849e5a7e323d985b742295309c5f414e_1cea83b3
core@ip-10-21-1-225 ~ $ docker logs 6cf808707d63
E0330 22:22:48.080881       1 proxier.go:197] Error removing userspace rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-PORTALS-HOST':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
E0330 22:22:48.081926       1 proxier.go:201] Error removing userspace rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-PORTALS-CONTAINER':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
E0330 22:22:48.082942       1 proxier.go:207] Error removing userspace rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-NODEPORT-HOST':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
E0330 22:22:48.084061       1 proxier.go:211] Error removing userspace rule: error checking rule: exit status 2: iptables v1.4.21: Couldn't load target `KUBE-NODEPORT-CONTAINER':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
E0330 22:22:48.085015       1 proxier.go:220] Error flushing userspace chain: error flushing chain "KUBE-PORTALS-CONTAINER": exit status 1: iptables: No chain/target/match by that name.
E0330 22:22:48.085892       1 proxier.go:220] Error flushing userspace chain: error flushing chain "KUBE-PORTALS-HOST": exit status 1: iptables: No chain/target/match by that name.
E0330 22:22:48.086803       1 proxier.go:220] Error flushing userspace chain: error flushing chain "KUBE-NODEPORT-HOST": exit status 1: iptables: No chain/target/match by that name.
E0330 22:22:48.087666       1 proxier.go:220] Error flushing userspace chain: error flushing chain "KUBE-NODEPORT-CONTAINER": exit status 1: iptables: No chain/target/match by that name.
E0330 22:22:48.088674       1 event.go:197] Unable to write event: 'Post https://10.21.1.10:443/api/v1/namespaces/default/events: dial tcp 10.21.1.10:443: connection refused' (may retry after sleeping)
E0330 22:22:48.428001       1 event.go:197] Unable to write event: 'Post https://10.21.1.10:443/api/v1/namespaces/default/events: dial tcp 10.21.1.10:443: connection refused' (may retry after sleeping)
E0330 22:22:58.428975       1 event.go:197] Unable to write event: 'Post https://10.21.1.10:443/api/v1/namespaces/default/events: dial tcp 10.21.1.10:443: connection refused' (may retry after sleeping)
core@ip-10-21-1-225 ~ $ curl -k -XPOST 'https://10.21.1.10:443/api/v1/namespaces/default/events'
Unauthorized
core@ip-10-21-1-225 ~ $ curl -k -XGET 'https://10.21.1.10:443/'
Unauthorized
core@ip-10-21-1-225 ~ $ docker exec -ti 6cf808707d63 /bin/bash
root@ip-10-21-1-225:/# curl -k -XPOST 'https://10.21.1.10:443/api/v1/namespaces/default/events'
Unauthorized
```

I've tried random things like rolling back the hyperkube version, IP ranges, instance types, etc.

Any idea what the problem might be?

**Comment by rwillard** [comment] 2016-03-30 23:21
Dunno too much, but the default hyperkube with the most recent release is v1.1.8_coreos.0. Also AWS permissions are very granular, could be a problem there? Good luck!

**Comment by colhom** [comment] 2016-03-31 18:44
@bkeroackdsc can you show me some of the output of `journalctl -u kubelet`on one of the worker nodes?

**Comment by jhuntoo** [comment] 2016-04-01 13:21
I am also experiencing this issue.

The output from `journalctl -u kubelet` on a worker is

`
Apr 01 09:53:40 ip-10-0-0-167 kubelet-wrapper[1163]: image: using image from file /usr/share/rkt/stage1-fly.aci
Apr 01 09:53:41 ip-10-0-0-167 kubelet-wrapper[1163]: image: searching for app image quay.io/coreos/hyperkube
Apr 01 09:53:41 ip-10-0-0-167 kubelet-wrapper[1163]: image: remote fetching from URL "https://quay.io/c1/aci/quay.io/coreos/hyperkube/v1.1.8_coreos.0/aci/linux/amd64/"
Apr 01 09:53:42 ip-10-0-0-167 kubelet-wrapper[1163]: pubkey: prefix: "quay.io/coreos/hyperkube"
Apr 01 09:53:42 ip-10-0-0-167 kubelet-wrapper[1163]: key: "https://quay.io/aci-signing-key"
Apr 01 09:53:42 ip-10-0-0-167 kubelet-wrapper[1163]: gpg key fingerprint is: BFF3 13CD AA56 0B16 A898  7B8F 72AB F5F6 799D 33BC
Apr 01 09:53:42 ip-10-0-0-167 kubelet-wrapper[1163]: Quay.io ACI Converter (ACI conversion signing key) <support@quay.io>
Apr 01 09:53:42 ip-10-0-0-167 kubelet-wrapper[1163]: Trusting "https://quay.io/aci-signing-key" for prefix "quay.io/coreos/hyperkube" without fingerprint review.
Apr 01 09:53:42 ip-10-0-0-167 kubelet-wrapper[1163]: Added key for prefix "quay.io/coreos/hyperkube" at "/etc/rkt/trustedkeys/prefix.d/quay.io/coreos/hyperkube/bff313cdaa560b16a8987b8f72abf5f6799d33bc"
Apr 01 09:53:42 ip-10-0-0-167 kubelet-wrapper[1163]: image: downloading signature from https://quay.io/c1/aci/quay.io/coreos/hyperkube/v1.1.8_coreos.0/aci.asc/linux/amd64/
Apr 01 09:53:42 ip-10-0-0-167 kubelet-wrapper[1163]: Downloading signature:  0 B/473 B
Apr 01 09:53:42 ip-10-0-0-167 kubelet-wrapper[1163]: Downloading signature:  473 B/473 B
Apr 01 09:53:44 ip-10-0-0-167 kubelet-wrapper[1163]: Downloading ACI:  0 B/81.7 MB
Apr 01 09:53:44 ip-10-0-0-167 kubelet-wrapper[1163]: Downloading ACI:  16.4 KB/81.7 MB
Apr 01 09:53:45 ip-10-0-0-167 kubelet-wrapper[1163]: Downloading ACI:  8.13 MB/81.7 MB
Apr 01 09:53:46 ip-10-0-0-167 kubelet-wrapper[1163]: Downloading ACI:  28.7 MB/81.7 MB
Apr 01 09:53:47 ip-10-0-0-167 kubelet-wrapper[1163]: Downloading ACI:  49.2 MB/81.7 MB
Apr 01 09:53:48 ip-10-0-0-167 kubelet-wrapper[1163]: Downloading ACI:  69.8 MB/81.7 MB
Apr 01 09:53:49 ip-10-0-0-167 kubelet-wrapper[1163]: Downloading ACI:  81.7 MB/81.7 MB
Apr 01 09:53:55 ip-10-0-0-167 kubelet-wrapper[1163]: image: signature verified:
Apr 01 09:53:55 ip-10-0-0-167 kubelet-wrapper[1163]: Quay.io ACI Converter (ACI conversion signing key) <support@quay.io>
Apr 01 09:54:38 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:38.435201    1163 aws.go:466] Zone not specified in configuration file; querying AWS metadata service
Apr 01 09:54:38 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:38.655944    1163 aws.go:575] AWS cloud filtering on tags: map[KubernetesCluster:k8s-qa7]
Apr 01 09:54:38 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:38.659828    1163 manager.go:128] cAdvisor running in container: "/system.slice/kubelet.service"
Apr 01 09:54:41 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:41.957662    1163 fs.go:108] Filesystem partitions: map[/dev/xvda9:{mountpoint:/var/lib/kubelet major:202 minor:9 fsType: blockSize:0} /dev/xvda3:{mountpoint:/etc/ssl/certs major:202 minor:3
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:41.966143    1163 manager.go:163] Machine: {NumCores:1 CpuFrequency:2494018 MemoryCapacity:3950571520 MachineID:c0bb99276bc74b86b88d83396764e3f7 SystemUUID:EC2455A2-2EA7-95F1-BF29-098718D9DE
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:41.995702    1163 manager.go:169] Version: {KernelVersion:4.4.6-coreos ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.10.3 CadvisorVersion: CadvisorRevision:}
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:41.997377    1163 server.go:798] Adding manifest file: /etc/kubernetes/manifests
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:41.997400    1163 server.go:808] Watching apiserver
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:42.258678    1163 plugins.go:56] Registering credential provider: .dockercfg
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:42.263778    1163 server.go:770] Started kubelet
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:42.263895    1163 kubelet.go:756] Image garbage collection failed: unable to find data for container /
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:42.269922    1163 kubelet.go:777] Running in container "/kubelet"
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:42.269961    1163 server.go:72] Starting to listen on 0.0.0.0:10250
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:42.322848    1163 event.go:197] Unable to write event: 'Post https://10.0.0.50:443/api/v1/namespaces/default/events: dial tcp 10.0.0.50:443: connection refused' (may retry after sleeping)
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:42.371652    1163 factory.go:197] System is using systemd
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:42.712058    1163 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:42.842450    1163 factory.go:239] Registering Docker factory
Apr 01 09:54:42 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:42.842998    1163 factory.go:93] Registering Raw factory
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:43.003518    1163 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:43.089573    1163 manager.go:1006] Started watching for new ooms in manager
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:43.090213    1163 oomparser.go:183] oomparser using systemd
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:43.090665    1163 manager.go:250] Starting recovery of all containers
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: W0401 09:54:43.187779    1163 container.go:326] Failed to create summary reader for "/system.slice/systemd-fsck-root.service": none of the resources are being tracked.
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: W0401 09:54:43.255624    1163 container.go:326] Failed to create summary reader for "/system.slice/system-systemd\\x2dfsck.slice": none of the resources are being tracked.
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:43.260924    1163 manager.go:255] Recovery completed
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:43.379217    1163 manager.go:104] Starting to sync pod status with apiserver
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:43.388300    1163 kubelet.go:1960] Starting kubelet main sync loop.
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:43.388363    1163 kubelet.go:1915] error getting node: node 'ip-10-0-0-167' is not in cache
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:43.431736    1163 kubelet.go:1356] Failed creating a mirror pod "kube-proxy-ip-10-0-0-167_kube-system": Post https://10.0.0.50:443/api/v1/namespaces/kube-system/pods: dial tcp 10.0.0.50:443:
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:43.437795    1163 kubelet.go:1361] Mirror pod not available
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:43.443564    1163 provider.go:91] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: W0401 09:54:43.466390    1163 manager.go:108] Failed to updated pod status: error updating status for pod "kube-proxy-ip-10-0-0-167_kube-system": Get https://10.0.0.50:443/api/v1/namespaces/kube-system/
Apr 01 09:54:43 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:43.499739    1163 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
Apr 01 09:54:44 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:44.357684    1163 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
Apr 01 09:54:46 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:46.020294    1163 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
Apr 01 09:54:48 ip-10-0-0-167 kubelet-wrapper[1163]: I0401 09:54:48.885772    1163 hairpin.go:49] Unable to find pair interface, setting up all interfaces: No peer_ifindex in interface statistics for eth0 of container 1241
Apr 01 09:54:49 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:49.289823    1163 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
Apr 01 09:54:51 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:51.812384    1163 event.go:197] Unable to write event: 'Post https://10.0.0.50:443/api/v1/namespaces/default/events: dial tcp 10.0.0.50:443: connection refused' (may retry after sleeping)
Apr 01 09:54:56 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:54:56.274286    1163 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
Apr 01 09:55:01 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:55:01.815904    1163 event.go:197] Unable to write event: 'Post https://10.0.0.50:443/api/v1/namespaces/default/events: dial tcp 10.0.0.50:443: connection refused' (may retry after sleeping)
Apr 01 09:55:03 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:55:03.472194    1163 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
Apr 01 09:55:10 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:55:10.537660    1163 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
Apr 01 09:55:11 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:55:11.824091    1163 event.go:197] Unable to write event: 'Post https://10.0.0.50:443/api/v1/namespaces/default/events: dial tcp 10.0.0.50:443: connection refused' (may retry after sleeping)
Apr 01 09:55:17 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:55:17.666557    1163 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
Apr 01 09:55:21 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:55:21.828361    1163 event.go:197] Unable to write event: 'Post https://10.0.0.50:443/api/v1/namespaces/default/events: dial tcp 10.0.0.50:443: connection refused' (may retry after sleeping)
Apr 01 09:55:24 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:55:24.725307    1163 kubelet.go:866] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
Apr 01 09:55:24 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:55:24.943411    1163 kubelet.go:1356] Failed creating a mirror pod "kube-proxy-ip-10-0-0-167_kube-system": Post https://10.0.0.50:443/api/v1/namespaces/kube-system/pods: dial tcp 10.0.0.50:443:
Apr 01 09:55:25 ip-10-0-0-167 kubelet-wrapper[1163]: E0401 09:55:24.943441    1163 kubelet.go:1361] Mirror pod not available`

**Comment by bkeroackdsc** [comment] 2016-04-01 17:32
Could this be related to https://github.com/kubernetes/kubernetes/issues/11543 ?

@colhom I'd have to provision a new cluster to get journalctl output. Hopefully @jhuntoo above gave you what you're looking for.

**Comment by colhom** [comment] 2016-04-01 17:35
It looks like the kubelet is failing to get the instance metadata from the AWS api.

@jhuntoo  what kubernetes version are you using? 1.1.8 or v1.2 ?

\cc @bkeroackdsc

**Comment by jhuntoo** [comment] 2016-04-04 12:40
@colhom  The error occurred after spinning up a cluster from a fresh clone on Friday. There is a reference in the kubelet log above appears to v1.1.8_coreos.0. Hope that helps.

**Comment by colhom** [comment] 2016-04-08 19:03
@jhuntoo I'm curious if you're still seeing this problem, or have reproduced it?

I've been noticing some transient "oddness" with the AWS APIs in the last week. I'm trying to figure out if your kubelet is not identifying the host ec2 instance properly, or if AWS was just misbehaving.

**Comment by bkeroackdsc** [comment] 2016-04-11 22:17
Given that the fix for https://github.com/kubernetes/kubernetes/issues/11543 didn't land until v1.2--and without the fix any use of ``--cloud-provider=aws`` is broken for me--seems to indicate that it is a k8s issue.

**Comment by aaronlevy** [comment] 2016-06-27 22:42
I'm going to close this as it seems to be an upstream related issue. Please re-open if there's still an ongoing issue here.

**Closed by aaronlevy** 2016-06-27 22:42 UTC
Labels: kind/support, platform/AWS, priority/P1
