### ISSUE TITLE
kube-aws: when things fail redirect to cloud formation webpage

### ISSUE THREAD

**Issue by ericchiang** [coreos/coreos-kubernetes#199] opened 2015-12-11 20:31 UTC
#hackday

It gives better error messages then the API.

**Comment by aaronlevy** [comment] 2015-12-15 18:07
I'm going to close this as duplicate of https://github.com/coreos/coreos-kubernetes/issues/195

More or less, we should expose as much info about errors as possible (and if available via web console, we should be able to get it via api)

**Closed by aaronlevy** 2015-12-15 18:07 UTC
Labels: reviewed/duplicate
