### ISSUE TITLE
docker0 can't get flanneld subnet

### ISSUE THREAD

**Issue by sysit** [coreos/coreos-kubernetes#698] opened 2016-09-29 07:24 UTC
docker opts is empty  in /etc/kubernetes/cni/docker_opts_cni.env

**Comment by pbx0** [comment] 2016-09-29 20:28
Is the file completely empty or is it resetting two environment variables ? If the later, that is by design as the CNI network plugin is now configuring the bridge that flannel uses. See: 

Otherwise, could you provide the exact tools you are using to set this up? (i.e. are you using the generic scripts or the kube-aws tool?)

**Comment by sysit** [comment] 2016-09-30 00:52
I‘m use multi-node/gereric scripts;  
the flanneld auto  create docker enviroments in  /run/flannel_docker_opts.env ,   but docker daemon read  drop-in file enviroments  in /etc/kubernetes/cni/docker_opts_cni.env;  

use contraller_install script create  /etc/kubernetes/cni/docker_opts_cni.env like this:
DOCKER_OPT_BIP=""
DOCKER_OPT_IPMASQ=""

so the docker daemon can't get flanneld subnet.

**Comment by pbx0** [comment] 2016-09-30 00:59
Right, I see how this is confusing. For a long time, we used those variables to tell the docker daemon what bridge IP to use for `docker0`. However, in kubernetes v1.3 we have the option to create a separate bridge via CNI plugins. Then kubernetes pods will tell docker that they wish to use this bridge instead of `docker0`.  

So we explicitly now set those variables to nothing so that `docker0` doesn't end up with the same IP address as `cni0`

See this commit for more details: https://github.com/coreos/coreos-kubernetes/commit/7ad134744b75d0a8a75af165afeb107ea245f87a
and a followup commit: https://github.com/coreos/coreos-kubernetes/commit/00591a27c6a51ae827e618d3d5dea9ff447e74c7

**Comment by sysit** [comment] 2016-09-30 02:41
sorry, I'm still stuck in k8s 1.2.4.

thanks a lot.

**Comment by pbx0** [comment] 2016-09-30 03:58
Oh I see why this caused you problems, it might be easiest to work from this repo at our v0.7.1 tag since that was tested with 1.2.4: https://github.com/coreos/coreos-kubernetes/releases/tag/v0.7.1

I'll close this for now, feel free to re-open if your still having problems getting flannel to work.

**Closed by pbx0** 2016-09-30 03:58 UTC
