### ISSUE TITLE
Make the tls assets expirations configurables. 

### ISSUE THREAD

**Issue by gleeb** [coreos/coreos-kubernetes#633] opened 2016-08-23 09:24 UTC
Why not allow generation of credentials and assets for production as well by configuring the expiration in days of these assets.

**Comment by aaronlevy** [comment] 2016-08-24 17:29
Closing as duplicate of: https://github.com/coreos/coreos-kubernetes/issues/621

**Closed by aaronlevy** 2016-08-24 17:29 UTC
