### ISSUE TITLE
tls: generate unlimited certs

### ISSUE THREAD

**Issue by philips** [coreos/coreos-kubernetes#627] opened 2016-08-21 20:36 UTC
The overwhelming user feedback is that people are surprised by the default 90 day certificate expiration. Lets create certificates that have no expiration by default and leave it to the user to upgrade or secure the system further.

I argue this is reasonable because other assets crucial to the cluster also default to this unlimited policy. For example SSH host keys.

**Comment by pieterlange** [comment] 2016-08-22 12:19
SSH host keys are not shared and don't have to survive the cluster's lifetime though.

Isn't it better to just make it easier to replace the certificates later on? @colhom already did a lot of work on that.

FWIW i generate my own certs with ridiculous 10y lifespans, but that's my own conscious decision.  :)

**Comment by wkruse** [comment] 2016-08-22 12:57
Duplicate of #621.

**Comment by pieterlange** [comment] 2016-08-22 13:02
There are a lot of duplicates for this issue indeed. I think it's worth mentioning TLS bootstrap will eventually be done natively: https://github.com/kubernetes/features/issues/43

Building certs with no expiration date to remove some friction for new users seems acceptable with that context :+1:

**Comment by aaronlevy** [comment] 2016-08-24 17:29
Closing as duplicate of: https://github.com/coreos/coreos-kubernetes/issues/621

**Closed by aaronlevy** 2016-08-24 17:29 UTC
Labels: help wanted, kind/enhancement, kind/friction, low hanging fruit, priority/P1
