### ISSUE TITLE
kube-aws: improve documentation of externalDNSName option

### ISSUE THREAD

**Issue by ericchiang** [coreos/coreos-kubernetes#194] opened 2015-12-11 19:54 UTC
#hackday

Currently:

```
This DNS name is assumed to be routable from outside the cluster to the Kubernetes API.
It is automatically added as a Subject Alternative Names (SANs) to the kube-apiserver TLS certificate.
```

Couple of questions
* Do I have to provision this before running `kube-aws up`?
* For development can I use a DNS name without actually provisioning a DNS name correctly?
* What IP address should this DNS name point to?

**Comment by jaxxstorm** [comment] 2015-12-19 09:58
+1 came here after googling and have no idea what I should be doing with this

**Comment by xied75** [comment] 2015-12-19 10:50
All it does is to make sure the TLS cert cover this "DNS" or "domain" name so later when you try to connect you can get a secure connection.

For testing purpose you don't need to get a real domain name at all, e.g. you can give it whatever name you like, I normally give it a "kube1". After my kube-aws up run finish and the public IP is printed, I just do"
```
sudo vi /etc/hosts
```
and add/edit a line:
```
52.16.92.202    kube1
```
Then
```
export KUBECONFIG=/home/dong/aws/kube-aws/clusters/kube1/kubeconfig
```
Now you are ready to fire your kubectl cmds.

**Comment by aaronlevy** [comment] 2015-12-28 19:55
related: https://github.com/coreos/coreos-kubernetes/issues/83

**Comment by aaronlevy** [comment] 2016-03-31 17:03
Closing as duplicate of https://github.com/coreos/coreos-kubernetes/issues/83

**Closed by aaronlevy** 2016-03-31 17:03 UTC
Labels: kind/documentation, platform/AWS, priority/P1
